# fly.toml app configuration file generated for chess-io-server on 2025-11-14T17:11:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chess-io-server'
primary_region = 'bom'

[build]
  dockerfile = './server/Dockerfile'
  args = { }

[env]
  PORT = '5000'
  NODE_ENV = 'production'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_checks]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'get'
    path = '/ping'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
